### ISSUE TITLE
pod search HEPhotoPicker 搜索不到

### ISSUE THREAD

**Issue by shether** [heyode/HEPhotoPicker#2]
pod search HEPhotoPicker 搜索不到

**Comment by heyode** [comment]
建议参考下：http://blog.sina.com.cn/s/blog_800cdf9c0102ve7e.html

**Comment by heyode** [comment]
我尝试了pod search HEPhotoPicker可以搜出来，但非常慢，大概花了20分钟
![image](https://user-images.githubusercontent.com/12412023/48877937-6a16d900-ee40-11e8-9bf0-43051e27cb9f.png)
