### ISSUE TITLE
访问相册问题

### ISSUE THREAD

**Issue by Ethanzhangyubo** [heyode/HEPhotoPicker#3]
Actual behavior and expected behavior（当前有什么问题以及你期望的结果)
如果相册的图片是在iCloud上，虽然图片的缩略图在相册上可以看见，但获取不到图片，获取图片为nil，如果图片是在本地就没有问题。
Steps to reproduce the problem（重现问题的步骤）

The version of the project and system version（软件版本，系统版本）

**Comment by MatoMA** [comment]
https://github.com/dfabreguette-ap/ImagePicker/commit/f79926ab3e27ee65030162a2ab7b11ece0053e88

**Comment by heyode** [comment]
0.0.8添加了对iCloud的支持
